name = "CascadeDecays"
uuid = "fffe189e-c188-4e56-b22b-870ae3b23d6b"
authors = ["Mikhail Mikhasenko"]
version = "0.1.0-DEV"

[deps]
FourVectors = "b122eb78-8380-428a-b8c8-584a022ae8b6"
HadronicLineshapes = "49c9d978-1f9d-4e96-a984-0a9783c0b9bf"
InstructionalDecayTrees = "1d606af4-d0f8-4ff7-bc8d-eb3f657b7647"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreeBodyDecays = "e6563dab-9ca1-5843-bde3-2ccf38d63843"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[sources]
FourVectors = {url = "https://github.com/mmikhasenko/FourVectors.jl"}
InstructionalDecayTrees = {url = "https://github.com/mmikhasenko/InstructionalDecayTrees.jl"}

[compat]
FourVectors = "0.3.4"
HadronicLineshapes = "0.4.2"
InstructionalDecayTrees = "0.2.1"
Literate = "2.21.0"
PartialWaveFunctions = "0.2"
StaticArrays = "1"
ThreeBodyDecays = "0.14.0"
Tullio = "0.3"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
